package com.rhfashon.app;

import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.content.*;import android.webkit.WebView;import android.webkit.WebViewClient;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.text.NumberFormat;import java.util.*;import java.util.concurrent.*;

public class MainActivity extends Activity {
    LinearLayout root, content, bottom; EditText search; TextView cartBadge; ExecutorService pool=Executors.newFixedThreadPool(4); int green=Color.rgb(7,138,75); int red=Color.rgb(229,43,43); int gray=Color.rgb(245,247,249);
    @Override public void onCreate(Bundle b){super.onCreate(b); getWindow().setStatusBarColor(Color.rgb(5,107,58)); showHome();}
    TextView tv(String s,float size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(12,8,12,8);return t;}
    GradientDrawable bg(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(r);return g;}
    LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    ScrollView scroll(LinearLayout l){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(l);return s;}
    void base(String title){root=col();root.setBackgroundColor(gray);setContentView(root); LinearLayout top=row();top.setPadding(8,6,8,6);top.setBackgroundColor(Color.WHITE);
        TextView logo=tv("R.H Fashon",21,green);logo.setTypeface(null,1);top.addView(logo,new LinearLayout.LayoutParams(0,52,1));
        TextView cart=tv("🛒",25,Color.DKGRAY);top.addView(cart,new LinearLayout.LayoutParams(55,52));cart.setOnClickListener(v->showCart());
        cartBadge=tv("",11,Color.WHITE);cartBadge.setGravity(Gravity.CENTER);cartBadge.setBackground(bg(red,50));top.addView(cartBadge,new LinearLayout.LayoutParams(28,28));
        root.addView(top);content=col();root.addView(content,new LinearLayout.LayoutParams(-1,0,1)); makeBottom(); updateBadge(); }
    void makeBottom(){bottom=row();bottom.setBackgroundColor(Color.WHITE); String[] a={"⌂\nহোম","▦\nক্যাটাগরি","🚚\nট্র্যাকিং","◯\nঅ্যাকাউন্ট"};for(int i=0;i<4;i++){final int x=i;TextView b=tv(a[i],13,Color.DKGRAY);b.setGravity(Gravity.CENTER);bottom.addView(b,new LinearLayout.LayoutParams(0,64,1));b.setOnClickListener(v->{if(x==0)showHome();else if(x==1)showCategories();else if(x==2)openWeb(Api.ACCOUNT);else openWeb(Api.ACCOUNT);});}root.addView(bottom);}
    void updateBadge(){if(cartBadge!=null){cartBadge.setText(Cart.count()>0?String.valueOf(Cart.count()):"");cartBadge.setVisibility(Cart.count()>0?View.VISIBLE:View.INVISIBLE);}}
    void showHome(){base("home"); LinearLayout pad=col();pad.setPadding(12,10,12,16);content.addView(pad); 
        LinearLayout sr=row();search=new EditText(this);search.setSingleLine();search.setHint("আপনার পছন্দ খুঁজুন...");search.setTextSize(16);search.setBackground(bg(Color.WHITE,50));sr.addView(search,new LinearLayout.LayoutParams(0,52,1));TextView go=tv("🔍",22,green);go.setGravity(Gravity.CENTER);sr.addView(go,new LinearLayout.LayoutParams(56,52));go.setOnClickListener(v->doSearch(search.getText().toString()));pad.addView(sr);
        TextView crawl=tv("🛒 R.H Fashon — সেরা পণ্য, সেরা দাম • দ্রুত ডেলিভারি!",14,Color.WHITE);crawl.setSingleLine();crawl.setBackground(bg(Color.rgb(45,50,55),0));pad.addView(crawl,new LinearLayout.LayoutParams(-1,42));
        TextView hero=tv("ফর্মাল শার্ট\n\nবিশেষ ছাড়ে পছন্দের পণ্য কিনুন\n\n       এখনই কিনুন →",22,Color.WHITE);hero.setTypeface(null,1);hero.setPadding(24,18,18,18);hero.setBackground(bg(green,28));LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,230);hp.setMargins(0,12,0,12);pad.addView(hero,hp);hero.setOnClickListener(v->doSearch("shirt"));
        LinearLayout hd=row();TextView h=tv("ক্যাটাগরি",25,Color.BLACK);h.setTypeface(null,1);hd.addView(h,new LinearLayout.LayoutParams(0,54,1));TextView all=tv("সব দেখুন →",16,green);hd.addView(all,new LinearLayout.LayoutParams(110,54));pad.addView(hd); 
        HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout cats=row();cats.setPadding(0,4,0,8);hs.addView(cats);pad.addView(hs,new LinearLayout.LayoutParams(-1,125));loadCategories(cats);
        TextView offer=tv("বড় অফার\n\nবিশেষ ছাড়ে আপনার পছন্দের পণ্য\n\n   এখনই কিনুন →",20,red);offer.setBackground(bg(Color.rgb(255,220,215),24));offer.setPadding(24,14,10,10);LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(-1,180);op.setMargins(0,8,0,8);pad.addView(offer,op);
        LinearLayout deal=row();TextView dt=tv("⚡ হট ডিল",25,Color.BLACK);dt.setTypeface(null,1);deal.addView(dt,new LinearLayout.LayoutParams(0,54,1));TextView da=tv("সব দেখুন →",16,green);deal.addView(da,new LinearLayout.LayoutParams(105,54));pad.addView(deal);
        LinearLayout grid=col();pad.addView(grid);loadProducts(grid,"per_page=8&orderby=date");
    }
    void loadCategories(LinearLayout host){get(Api.CATEGORIES+"?per_page=10&hide_empty=true",json->{runOnUiThread(()->{try{for(int i=0;i<json.length();i++){JSONObject o=json.getJSONObject(i);TextView c=tv("🛍️\n"+o.optString("name"),13,Color.DKGRAY);c.setGravity(Gravity.CENTER);c.setBackground(bg(Color.WHITE,28));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(110,108);p.setMargins(4,4,8,4);host.addView(c,p);int id=o.optInt("id");c.setOnClickListener(v->showCategory(id,o.optString("name")));}}catch(Exception e){}});});}
    void loadProducts(LinearLayout host,String query){get(Api.PRODUCTS+"?"+query,json->{runOnUiThread(()->{try{LinearLayout r=null;for(int i=0;i<json.length();i++){if(i%2==0){r=row();host.addView(r,new LinearLayout.LayoutParams(-1,0,1));}JSONObject o=json.getJSONObject(i);View card=productCard(o);r.addView(card,new LinearLayout.LayoutParams(0,270,1));} }catch(Exception e){}});});}
    View productCard(JSONObject o){LinearLayout c=col();c.setPadding(7,7,7,7);c.setBackground(bg(Color.WHITE,20));int id=o.optInt("id");String name=o.optString("name","Product");double price=price(o);String img="";try{img=o.getJSONArray("images").optJSONObject(0).optString("src");}catch(Exception ignored){}ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);c.addView(im,new LinearLayout.LayoutParams(-1,145));loadImage(im,img);TextView n=tv(name,14,Color.DKGRAY);n.setMaxLines(2);c.addView(n,new LinearLayout.LayoutParams(-1,48));TextView p=tv(bdt(price),17,green);p.setTypeface(null,1);c.addView(p);c.setOnClickListener(v->showProduct(o));return c;}
    double price(JSONObject o){try{return o.getJSONObject("prices").optDouble("price",0)/100.0;}catch(Exception e){return 0;}}
    String bdt(double n){return "৳"+String.format(Locale.US,"%,.2f",n);}
    void showProduct(JSONObject o){base("product");LinearLayout p=col();p.setPadding(12,12,12,18);content.addView(scroll(p),new LinearLayout.LayoutParams(-1,0,1));String img="";try{img=o.getJSONArray("images").optJSONObject(0).optString("src");}catch(Exception ignored){}ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_INSIDE);p.addView(im,new LinearLayout.LayoutParams(-1,310));loadImage(im,img);TextView name=tv(o.optString("name"),24,Color.BLACK);name.setTypeface(null,1);p.addView(name);double price=price(o);TextView pr=tv(bdt(price),23,green);pr.setTypeface(null,1);p.addView(pr);TextView desc=tv(strip(o.optString("short_description",o.optString("description",""))),15,Color.DKGRAY);p.addView(desc);Button add=new Button(this);add.setText("🛒  কার্টে যোগ করুন");add.setTextColor(Color.WHITE);add.setBackground(bg(green,18));p.addView(add,new LinearLayout.LayoutParams(-1,56));add.setOnClickListener(v->{String imurl=img;Cart.add(new Cart.Item(o.optInt("id"),o.optString("name"),imurl,price));updateBadge();Toast.makeText(this,"কার্টে যোগ হয়েছে",Toast.LENGTH_SHORT).show();});}
    String strip(String s){return s.replaceAll("<[^>]*>"," ").replaceAll("\\s+"," ").trim();}
    void showCategory(int id,String name){base("category");LinearLayout p=col();p.setPadding(10,8,10,16);content.addView(scroll(p),new LinearLayout.LayoutParams(-1,0,1));TextView h=tv(name,25,Color.BLACK);h.setTypeface(null,1);p.addView(h);LinearLayout grid=col();p.addView(grid);loadProducts(grid,"category="+id+"&per_page=20&orderby=date");}
    void showCategories(){base("categories");LinearLayout p=col();p.setPadding(12,12,12,20);content.addView(scroll(p),new LinearLayout.LayoutParams(-1,0,1));TextView h=tv("সব ক্যাটাগরি",25,Color.BLACK);h.setTypeface(null,1);p.addView(h);loadCategories(p);}
    void doSearch(String q){if(q==null||q.trim().isEmpty())return;base("search");LinearLayout p=col();p.setPadding(10,8,10,20);content.addView(scroll(p),new LinearLayout.LayoutParams(-1,0,1));TextView h=tv("সার্চ: "+q,22,Color.BLACK);p.addView(h);LinearLayout g=col();p.addView(g);loadProducts(g,"search="+enc(q));}
    void showCart(){base("cart");LinearLayout p=col();p.setPadding(10,10,10,20);content.addView(scroll(p),new LinearLayout.LayoutParams(-1,0,1));TextView h=tv("🛒 আপনার কার্ট",24,Color.BLACK);h.setTypeface(null,1);p.addView(h);for(Cart.Item i:Cart.all()){LinearLayout r=row();r.setPadding(5,8,5,8);ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);r.addView(im,new LinearLayout.LayoutParams(90,90));loadImage(im,i.image);LinearLayout mid=col();mid.addView(tv(i.name,15,Color.DKGRAY));mid.addView(tv(bdt(i.price),16,green));r.addView(mid,new LinearLayout.LayoutParams(0,100,1));Button minus=new Button(this);minus.setText("−");r.addView(minus,new LinearLayout.LayoutParams(50,50));TextView q=tv(String.valueOf(i.qty),16,Color.BLACK);q.setGravity(Gravity.CENTER);r.addView(q,new LinearLayout.LayoutParams(35,50));Button plus=new Button(this);plus.setText("+");r.addView(plus,new LinearLayout.LayoutParams(50,50));minus.setOnClickListener(v->{Cart.dec(i.id);showCart();});plus.setOnClickListener(v->{Cart.inc(i.id);showCart();});p.addView(r);}
        TextView total=tv("মোট: "+bdt(Cart.total()),22,green);total.setTypeface(null,1);p.addView(total);Button checkout=new Button(this);checkout.setText("Checkout →");checkout.setTextColor(Color.WHITE);checkout.setBackground(bg(green,18));p.addView(checkout,new LinearLayout.LayoutParams(-1,58));checkout.setOnClickListener(v->openWeb(Api.CHECKOUT));}
    void openWeb(String url){base("web");WebView w=new WebView(this);w.getSettings().setJavaScriptEnabled(true);w.getSettings().setDomStorageEnabled(true);w.setWebViewClient(new WebViewClient());w.loadUrl(url);content.addView(w,new LinearLayout.LayoutParams(-1,0,1));}
    String enc(String s){try{return URLEncoder.encode(s,"UTF-8");}catch(Exception e){return s;}}
    void get(String url,Callback cb){pool.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setRequestProperty("Accept","application/json");c.setConnectTimeout(12000);c.setReadTimeout(15000);BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder s=new StringBuilder();String x;while((x=r.readLine())!=null)s.append(x);r.close();cb.ok(new JSONArray(s.toString()));}catch(Exception e){cb.ok(new JSONArray());}});}
    interface Callback{void ok(JSONArray j);}
    void loadImage(ImageView v,String url){if(url==null||url.isEmpty())return;pool.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(8000);c.setReadTimeout(10000);InputStream in=c.getInputStream();android.graphics.Bitmap b=android.graphics.BitmapFactory.decodeStream(in);in.close();runOnUiThread(()->{if(b!=null)v.setImageBitmap(b);});}catch(Exception ignored){}});}
    @Override public void onBackPressed(){super.onBackPressed();}
}
